### ISSUE TITLE
Update README to explain why this project was started, its goals, and current status

### ISSUE THREAD

**Issue by davelab6** [fonttools/ufoLib2#2]
The README is extremely terse ;)

**Comment by anthrotype** [comment]
we don't want to publicize this too much as it's mostly an experiment for now.
The plan is to eventually merge this into fontTools, i.e. `fontTools.ufoLib.objects` module.
The current status is, we finally have `fontTools.ufoLib`, which is the same as the current standalone ufoLib, so just the UFOReader and UFOWriter.
In PR #6 I am changing ufoLib2 to use the new fontTools.ufoLib for reader/writer.
ufo2ft already runs its own tests with both defcon and ufoLib2.
We'll continue from there and we'll see how it goes.

**Comment by benkiel** [comment]
@anthrotype Am I correct in understanding the work here is for the lightweight version of defcon? If so, you may want to change the name of this to ufoLib.objects (ufoLibObjects?) to make it more clear. One other question: are you keeping the API the same as Defcon?

**Comment by madig** [comment]
The plan is to end up as `fontTools.ufoLib.objects`, yes, as a lightweight defcon meant for UFO processing rather than editing. Cosimo and me were thinking of proposing it as such soon-ish. There are some minor API differences, but last I heard, the goal was to stay compatible where it makes sense. It could also serve as a vehicle to change the API where appropriate.

**Comment by benkiel** [comment]
Got it. Just wanted to clarify. Thanks for the info

**Comment by madig** [comment]
Updated the Readme with some info.
