### ISSUE TITLE
`bounds` and `controlPointBounds` property for Glyph and Contour?

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#22]
May be useful to have? Can use the available pens and `draw*` methods.

**Comment by anthrotype** [comment]
you'd need a reference to the glyph's layer in order to compute bounds for composite glyphs, and currently ufoLib2 Glyph objects don't have a back-reference to their parent layer, because I'm not convinced it's a good idea to maintain circular parent-children references.

We could add method (getBounds and getControlPointBounds) to the Glyph class that take the glyphSet as an optional parameter and call the right pens returning the bbox tuple

**Comment by madig** [comment]
This would also enable `leftMargin` and `rightMargin`, maybe even with setters.

**Comment by madig** [comment]
Note to self:

> take the glyphSet as an optional parameter

Which is only necessary if the glyph contains a component.
