### ISSUE TITLE
PANOSE values lost

### ISSUE THREAD

**Issue by aaronbell** [fonttools/ufoLib2#40]
I'm generating a UFO using the `from_designspace` and `generate_instance` commands, but discovered that the UFO produced at the other end has lost its PANOSE data that was present in the original file, so I have to re-add the info after the fact.

Currently using ufolib2 0.4.0

**Comment by madig** [comment]
Hi! I presume you are using fontmake's instantiator module. Panose is tossed on purpose because it contains a weight component that cannot be straightforwardly generated from the weight axis (if you know an algorithm, please tell us!). If you use the module directly, you'll have no choice but to insert the panose values after generating an instance.

**Comment by aaronbell** [comment]
Ahhh, makes sense. OK. I'll just have to modify PANOSE after the fact then.
