### ISSUE TITLE
Glif: do not write empty outline element

### ISSUE THREAD

**Issue by madig** [fonttools/ufoLib2#49]
ufonormalizer removes it e.g. for `/space`.

**Comment by anthrotype** [comment]
should this be done in ufoLib2 or in fontTools.ufoLib.UFOWriter?

**Comment by madig** [comment]
Probably in UFOWriter 🤔

**Comment by anthrotype** [comment]
this should happen in the UFOWriter, specifically in glyfLib.GlyphSet.

https://github.com/fonttools/fonttools/blob/ad4bc6f151081ddedcc09c9791d424455b529d7c/Lib/fontTools/ufoLib/glifLib.py#L599-L606

But I anticipate resistance on this point because (unlike the infrequent empty fontinfo.plist) this will change the majority of UFOs out there (not semantically, but from a text diffing point of view).

The fact that there is even provision in the current code for preventing lxml to write self-closing tags when outline element is empty makes me think that it won't be an easy change to make.

Also, it's not the end of the world.

**Comment by madig** [comment]
It would be one step towards making ufonormalizer obsolete, at least... oh well.
